### ISSUE TITLE
Some issues found on the amazing homepage ;)

### ISSUE THREAD

**Issue by hanlin-he** [runzezhang/runzezhang.github.io#1]
I think some of the following might be an issue. If you don't mind I started the thread~

-   Skills display position exceeded the frame in wide screen. The width for the text box might be adjusted incorrectly.
    ![image](https://user-images.githubusercontent.com/15765440/38889611-1bb9779e-4234-11e8-8653-02fdefd0ee2a.png)

-    The `See fully description` link for all projects are 404, for example http://runzezhang.com/projects/2018/04/12/Bio-COMPASS/.
    The date in the links are all wrong. The links inside the `project` section are correct.

-   There is a typo in **My Track** section, `Peiking -> Peking`.

-   For some reason, this link is 404: http://runzezhang.com/archives

-   The `source code` link in tetris game was wrong.
    ![image](https://user-images.githubusercontent.com/15765440/38890775-3929085a-4237-11e8-9102-7f10145c8dda.png)

-   The pic in Breakout is missing.
    ![image](https://user-images.githubusercontent.com/15765440/38890905-9a146b32-4237-11e8-952c-559f2698e9ee.png)

**Comment by runzezhang** [comment]
# Update
## Bugs Fixed
- Skills display position exceeded the frame in wide screen. The width for the text box might be adjusted incorrectly.
- The See fully description link for all projects are 404, for example 
- There is a typo in My Track section, Peiking -> Peking.
- The source code link in tetris game was wrong.
- The pic in Breakout is missing.

## Not Found
For some reason, this link is 404: http://runzezhang.com/archives

Where u find this link? It seems I don't use it.
